spring:
  application:
    name: clon-trello
  datasource:
    # URL configurada para guardar los datos en un archivo físico en lugar de la memoria RAM
    url: jdbc:h2:file:./data/trello_db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
